# Generated by Django 3.2.8 on 2022-02-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='user',
        ),
        migrations.DeleteModel(
            name='CollectionImage',
        ),
        migrations.DeleteModel(
            name='UserCollection',
        ),
    ]
