# Generated by Django 3.2.8 on 2022-02-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='base_uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='chain_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='collection_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='dimension_x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='dimension_y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='image_uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='minting_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
