# Generated by Django 3.2.8 on 2022-02-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0004_auto_20220221_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollectionmint',
            name='collection_name_slug',
            field=models.SlugField(default='collection_name'),
            preserve_default=False,
        ),
    ]
