# Generated by Django 3.2.8 on 2022-02-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220207_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='metadata',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='path',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='path_compressed',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
