# Generated by Django 3.2.8 on 2022-02-20 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userproblemreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollectionmint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usercollectionmint',
            name='fully_minted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercollectionmint',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercollectionmint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserCollectionMintPublic',
        ),
    ]
