# Generated by Django 3.2.8 on 2022-03-03 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usercollectionmint_collection_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedusercollection_tracker',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usercollection'),
        ),
        migrations.AlterField(
            model_name='usercollectionmint',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usercollection'),
        ),
        migrations.AlterField(
            model_name='usercollectionmint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
