# Generated by Django 3.2.8 on 2022-02-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userproblemreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollectionmint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usercollectionmint',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserCollectionMintPublic',
        ),
    ]
