# Generated by Django 3.2.8 on 2022-02-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220208_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credits',
        ),
    ]
