# Generated by Django 3.2.8 on 2021-12-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usercollection_duplicates_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollection',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
