# Generated by Django 3.2.8 on 2022-02-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220207_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='metadata',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='path_compressed',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
