# Generated by Django 3.2.8 on 2022-02-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220207_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='path',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='path_compressed',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
