# Generated by Django 3.2.8 on 2022-01-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='usd', max_length=100),
        ),
    ]
