# Generated by Django 3.2.8 on 2022-01-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
